OBJ = getch.o gettoken.o

.PHONY: all
all:
	make dcl undcl

undcl: $(OBJ) undcl.o
	cc -o undcl $(OBJ) undcl.o

dcl: $(OBJ) dcl.o
	cc -o dcl $(OBJ) dcl.o

undcl.o: gettoken.h

dcl.o: gettoken.h contains.h

gettoken.o: gettoken.h getch.h

getch.o: 

contains.o: 

.PHONY: clean
clean:
	rm -rf dcl undcl *.o
